In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('C:/Users/user/Desktop/lecfile/nov/221108/RNAseq_result.xlsx')

In [ ]:
df

In [ ]:
df.head(2)

## 실습
1. 의미없는 데이터를 제거하기
1. 유전자 발현이 있는 데이터만 남기기 (모두 0인 값 제거)
1. Treat 1 - 4 , 2 - 5. 3 - 6 은 비슷한 데이터이므로 평균값만 남기기
1. 결측치가 있으면 해당 row는 제거한다.

In [ ]:
#unnamed0 열 삭제

df = df.drop([df.columns[0]], axis = 1)

In [ ]:
df

In [ ]:
# 결측치가 있는 경우 행 전체를 삭제

# 행 별로 결측치가 있는지 확인한다.
# 만약 결측치가 하나라도 있을 경우에는 해당 row 전체를 제거한다.
delete1 = []

for i in range(len(df.index)):
    
    if any(df.iloc[i].isnull()) == True:
        delete1.append(i)
    
df = df.drop(index = delete1, axis = 0)

In [ ]:
df

In [ ]:
# 의미 없는 데이터 제거
# 전부 0인 값 제거

# 값을 전부 더했을 때 값이 0이라면 그 행 전체를 삭제한다.


delete2 = []

def fn1(x):
    delete2.append(x)

[fn1(i) for i in range(len(df.index)) if df.iloc[i,1:].sum() == 0.0]

df = df.drop(index = delete2, axis = 0)

In [ ]:
df

In [ ]:
# 1-4 2-5 3-6 데이터는 각각 부분의 평균을 내서 새로운 열에 저장하고 삭제.
import numpy as np
# np.mean([df.iloc[0,4],df.iloc[0,7]])

df['mean1-4'] = [np.mean([df.iloc[i,4],df.iloc[i,7]]) for i in range(len(df.index))]
df['mean2-5'] = [np.mean([df.iloc[i,5],df.iloc[i,8]]) for i in range(len(df.index))]
df['mean3-6'] = [np.mean([df.iloc[i,6],df.iloc[i,9]]) for i in range(len(df.index))]

df = df.drop(['Treat1','Treat2','Treat3','Treat4','Treat5','Treat6'], axis = 1)

In [ ]:
df

In [ ]:
## 강의안
mask = []

for i in df.index:
    if df.iloc[i, 1:].sum() == 0.0:
        mask.append(True)
    else:
        mask.append(False)
        
df[[not m for m in mask]]

In [ ]:
### 강의안
df['Treat1_4mean'] = df[['Treat1','Treat4']].mean(axis=1)

## 실습 -실제 데이터 전처리

* 어느 센터에서 
* 어떤 강좌를  
* 누가
* 얼마나
* 누구한테 진행했는지 정리<br><br>

* 데이터프레임 형태로 나타내기

* 필요 없는 부분 잘라내기
    * 교육방법구분, 운영요일, 강좌정원수, 데이터기준일자 열은 무관하므로 삭제
* 결측치가 있는 경우를 먼저 처리..
    * 결측치가 있다면 그 값을...
* 센터 별로 정렬
* 정렬한 내용 내에서 어떤 강좌가 있었는지 가나다순 정렬
* 얼마나...? 
    * 같은 강좌의 경우 총 시작일자와 종료일자를 파악해 합쳐서 띄운다.

In [ ]:
df_09 = pd.read_csv('C:/Users/user/Desktop/lecfile/nov/221116/시청자미디어재단_체험형미디어교육_20221109.csv', encoding = 'cp949')

In [ ]:
df_09

In [ ]:
df_09 = df_09.iloc[:,0:7]

In [ ]:
df_09['센터명'].unique()

In [ ]:
df_09.iloc[0,0]

In [ ]:
# nm = input('미디어센터 소재지 입력 : ') + '시청자미디어센터'
# mask = []

# for i in range(len(df_09.index)):
    
#     if df_09.iloc[i,0] == nm:
#         mask.append(True)
#     else:
#         mask.append(False)
        
# df_09[[m for m in mask]]

In [ ]:
df_09_01 = df_09.sort_values(by = ['센터명', '강좌명'])

In [ ]:
df_09_01

In [ ]:
df_09_01.iloc[0,3].split('-')[2]

df_09_01['교육시작일자'] = [df_09_01.iloc[i,3].split('-')[2] for i in range(len(df_09_01.index))]

In [ ]:
df_09_01['교육종료일자'] = [df_09_01.iloc[i,4].split('-')[2] for i in range(len(df_09_01.index))]

In [ ]:
def date_re(x):
    return int(df_09_01.iloc[x,4])-int(df_09_01.iloc[x,3])+1
    
    
df_09_01['교육기간'] = [date_re(i) for i in range(len(df_09_01.index))]

In [ ]:
df_09_01['교육기간'] = df_09_01['교육기간'].apply(lambda x : -x if x<0 else x)

In [ ]:
df_09_01['교육기간'].unique()

In [ ]:
df_09_01 = df_09_01.drop(['교육시작일자','교육종료일자'], axis = 1)

In [ ]:
df_09_01

In [ ]:
df_09_01['강좌명'].unique()

In [ ]:
df_09_01['강좌명'] = df_09_01['강좌명'].apply(lambda x: '찾아가는미디어나눔버스 체험' if '찾아가는미디어나눔버스 체험 교육' in x else x)

In [ ]:
df_09_01['강사명'].unique()

In [ ]:
# 외 몇명이나 미정은 기타로 바꾸자.
df_09_01['강사명'] = df_09_01['강사명'].apply(lambda x : '기타' if x == '미정' else x)

In [ ]:
df_09_01['강사명'] = df_09_01['강사명'].apply(lambda x: [x.split('외')[0], '기타'] if '외' in x else x )

In [ ]:
for i in df_09_01['강사명']:
    print(i)

In [ ]:
# , 로 구분된 강사명은 리스트 리턴을 해주자.

df_09_01['강사명'] = df_09_01['강사명'].apply(lambda x: x.split(',') if ',' in x else x)

In [ ]:
df_09_02 = df_09_01.drop(['강좌내용'], axis=1)

In [ ]:
df_09_01['교육대상구분'].unique()

In [ ]:
df_09_02

---
##  과제 제주시 데이터
1. 행정시별로 몇 개의 데이터가 포함되어 있는지 표기하기
1. 가맹점명을 가나다 순서(한글-영문-숫자-특문 오름차순) 으로 정렬하기
1. 전화번호에서 중간 번호가 600번대인 것과 700번대인 것 중 어느것이 많은지 확인하기
1. 주소를 길 이름만 남기기

In [3]:
import pandas as pd
df = pd.read_csv('C:/Users/user/Desktop/lecfile/nov/221116/제주특별자치도_아동급식카드가맹점현황_20220331.csv', encoding = 'cp949')

In [4]:
# 일단 행정시 내에 어떤 것이 있는지 확인
# 두 개 밖에 없다.

df['행정시'].unique()

array(['제주시', '서귀포시'], dtype=object)

In [5]:
# 제주시와 서귀포시로 갯수를 나눈다.

df_si = pd.DataFrame( columns = ['제주시', '서귀포시'])

j = 0
s = 0

for i in df['행정시']:
    
    if i == '제주시':
        j += 1

    else:
        s += 1
        
df_si.loc[len(df_si)] = [j, s]

In [6]:
# 이렇게 할 수 있다

pd.DataFrame(df['행정시'].value_counts())

        행정시
제주시   12931
서귀포시   5423

In [7]:
df_si

     제주시  서귀포시
0  12931  5423

In [8]:
# 가맹점명을 가나다 순서(한글-영문-숫자-특문-한자? 오름차순) 으로 정렬하기
# 일단 한번 오름차순 정렬을 해 보자

df.sort_values(by = ['가맹점명']).head(50)

,행정시,가맹점명,전화번호,주소,데이터기준일자
13278,제주시,(사복)한라원장애인직업재활시설,064-799-9225,제주특별자치도 제주시 애월읍 하소로 747-23,2022-03-31
4897,제주시,(유)경화산업,064-743-2111,제주특별자치도 제주시 용담이동 2038,2022-03-31
5567,제주시,(유)섬이다,064-745-5008,제주특별자치도 제주시 서해안로 452,2022-03-31
5744,제주시,(유)아웃백제주점,064-746-1591,제주특별자치도 제주시 노형동 1288-5,2022-03-31
4421,서귀포시,(유)케이디에셋 담앤루 밀탑,064-739-6611,제주특별자치도 서귀포시 이어도로343번길 63,2022-03-31
4958,제주시,(주) 우리마트그랜드점,064-743-5000,제주특별자치도 제주시 연북로 444,2022-03-31
10986,제주시,(주)가미유통,064-784-0028,제주특별자치도 제주시 조천읍 조천리 3203,2022-03-31
13731,제주시,(주)거멍축산,070-4411-5133,제주특별자치도 제주시 중앙로8길 11,2022-03-31
14350,서귀포시,(주)굿잡제주,NaN,제주특별자치도 서귀포시 대포로 174,2022-03-31
4711,제주시,(주)그랜드부민,064-742-5000,제주특별자치도 제주시 연북로 378,2022-03-31
11101,서귀포시,(주)그리운바다성산포,064-784-2128,제주특별자치도 서귀포시 성산읍 성산등용로 94,2022-03-31
1105,제주시,(주)금강축산유통,064-713-3010,제주특별자치도 제주시 서해안로 167,2022-03-31
839,제주시,(주)금관유통,064-712-4002,제주특별자치도 제주시 오일장중길 73,2022-03-31
2126,제주시,(주)금나유통,064-723-8151,제주특별자치도 제주시 거로남4길 4,2022-03-31
13975,서귀포시,(주)나린아토(표선회관),070-8691-0391,제주특별자치도 서귀포시 표선면 표선중앙로 90,2022-03-31
13603,서귀포시,(주)남원하나로축산유통,064-904-1192,제주특별자치도 서귀포시 홍중로 57,2022-03-31
11396,제주시,(주)낭뜰에쉼팡,064-784-9292,제주특별자치도 제주시 조천읍 남조로 2343,2022-03-31
5625,제주시,(주)뉴월드노형점,064-745-7411,제주특별자치도 제주시 월랑로10길 14,2022-03-31
572,제주시,(주)뉴월드마트로연동점,064-711-7151,제주특별자치도 제주시 선반로8길 5-7,2022-03-31
6926,제주시,(주)뉴월드마트로일도점,064-751-4600,제주특별자치도 제주시 연수로3길 6,2022-03-31
7993,제주시,(주)뉴월드마트로탑동점,064-756-6900,제주특별자치도 제주시 중앙로 13,2022-03-31
1389,제주시,(주)뉴월드서사라점,064-721-4601,제주특별자치도 제주시 삼도일동 520,2022-03-31
5559,제주시,(주)뉴월드신제주점,064-745-4600,제주특별자치도 제주시 연동12길 3,2022-03-31
2787,제주시,(주)뉴월드이도센트럴점,064-726-6900,제주특별자치도 제주시 중앙로 346,2022-03-31
5228,제주시,(주)뉴월드이도점,064-744-4600,제주특별자치도 제주시 승천로 63,2022-03-31
2786,제주시,(주)뉴월드화북점,064-726-6900,제주특별자치도 제주시 일주동로 233,2022-03-31
6920,제주시,(주)다모아미래컨벤션센터지점,064-751-3838,제주특별자치도 제주시 남성로 75,2022-03-31
13084,제주시,(주)다인리조트,064-799-2612,제주특별자치도 제주시 애월읍 고내리 79-8,2022-03-31
6888,제주시,(주)대양지에프에스(아라미당한우전문점),064-751-2266,제주특별자치도 제주시 아연로 595,2022-03-31
3767,서귀포시,(주)대유산업,064-738-0500,제주특별자치도 서귀포시 상예로 381,2022-03-31
4886,제주시,(주)대한에프앤비,064-743-1812,제주특별자치도 제주시 일주동로 180-1,2022-03-31
1283,서귀포시,(주)대한항공민속촌/한라점식당,064-720-6621,제주특별자치도 서귀포시 표선면 민속해안로 631-34,2022-03-31
15236,제주시,(주)돈짬노형점,NaN,제주특별자치도 제주시 1100로 3320,2022-03-31
17907,제주시,(주)두루두루,NaN,제주특별자치도 제주시 탑동로2길 3,2022-03-31
13016,제주시,(주)디엔씨지슬,064-799-1259,제주특별자치도 제주시 애월읍 평화로 2157,2022-03-31
301,제주시,(주)뚱보네,064-711-0977,제주특별자치도 제주시 정존11길 22,2022-03-31
452,제주시,(주)뚱보네,064-711-3953,제주특별자치도 제주시 정존11길 22,2022-03-31
17325,제주시,(주)라이스나이스,NaN,제주특별자치도 제주시 원당로3길 17,2022-03-31
4533,서귀포시,(주)롯데리아/엔제리너스제주중문,064-739-9611,제주특별자치도 서귀포시 중문관광로72번길 29-5,2022-03-31
13439,제주시,(주)멀씨,064-900-4053,제주특별자치도 제주시 애월읍 중엄안3길 22,2022-03-31
16700,제주시,(주)모스우드,NaN,제주특별자치도 제주시 애월읍 도치돌길 289-13,2022-03-31
17028,제주시,(주)무한야끼 아라점,NaN,제주특별자치도 제주시 연북로 514,2022-03-31
13312,서귀포시,(주)베이힐/레스토랑박수기정,064-801-9000,제주특별자치도 서귀포시 하예동 1888,2022-03-31
13266,제주시,(주)본태인터네셔널,064-799-8900,제주특별자치도 제주시 애월읍 애월북서길 56-1,2022-03-31
2742,제주시,(주)비엔올더타임,064-726-4868,제주특별자치도 제주시 원노형남1길 11,2022-03-31
13995,제주시,(주)쁠랑뜨,070-8809-5699,제주특별자치도 제주시 1100로 2977-15,2022-03-31
10974,제주시,(주)산굼부리,064-783-9900,제주특별자치도 제주시 조천읍 교래리 산38,2022-03-31
9575,서귀포시,(주)산티아고가는길 남원점,064-764-6131,제주특별자치도 서귀포시 남원읍 한신로 197,2022-03-31
571,제주시,(주)삼다도횟집,064-711-7080,제주특별자치도 제주시 서해안로 572,2022-03-31
15565,제주시,(주)삼아디앤씨,NaN,제주특별자치도 제주시 구좌읍 월정1길 54-10,2022-03-31

In [9]:
set([i[0] for i in df['가맹점명']])

{'(',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'P',
 'R',
 'S',
 'T',
 'W',
 'c',
 'e',
 'l',
 'm',
 '味',
 '美',
 '가',
 '각',
 '간',
 '갈',
 '감',
 '갑',
 '갓',
 '강',
 '개',
 '객',
 '갤',
 '갬',
 '갯',
 '갱',
 '거',
 '건',
 '걷',
 '걸',
 '검',
 '게',
 '겐',
 '겔',
 '겟',
 '겨',
 '견',
 '결',
 '겸',
 '겹',
 '경',
 '곁',
 '계',
 '고',
 '곤',
 '골',
 '곰',
 '곱',
 '곳',
 '공',
 '곶',
 '과',
 '곽',
 '관',
 '광',
 '괜',
 '괴',
 '괸',
 '굄',
 '교',
 '구',
 '국',
 '군',
 '굴',
 '굼',
 '굽',
 '굿',
 '궁',
 '권',
 '귀',
 '규',
 '귤',
 '그',
 '근',
 '글',
 '금',
 '기',
 '긴',
 '길',
 '김',
 '깃',
 '깅',
 '깊',
 '까',
 '깐',
 '깔',
 '깜',
 '깡',
 '깨',
 '꺼',
 '꼬',
 '꼭',
 '꼴',
 '꼼',
 '꽁',
 '꽃',
 '꽈',
 '꾸',
 '꾹',
 '꾼',
 '꿀',
 '꿈',
 '꿉',
 '꿩',
 '뀨',
 '끄',
 '끌',
 '끼',
 '나',
 '낙',
 '낚',
 '난',
 '날',
 '남',
 '낫',
 '낭',
 '낮',
 '낯',
 '내',
 '냄',
 '냉',
 '너',
 '넉',
 '넘',
 '넙',
 '넝',
 '네',
 '넥',
 '노',
 '녹',
 '논',
 '놀',
 '놈',
 '농',
 '높',
 '누',
 '눈',
 '눕',
 '뉴',
 '느',
 '늘',
 '능',
 '니',
 '닌',
 '닐',
 '다',
 '닥',
 '단',
 '달',
 '닭',
 '담',
 '당',
 '닻',
 '대',
 '댄',
 '댓',
 '댜',
 '더',
 '덕',
 '던',
 '덤',
 '덩',
 '덮',
 '데',
 '덴',
 '델',
 '도',
 '독',
 '돈',
 '돌',
 '돎',
 '돔',
 '돗',
 '동',
 '돛',
 '돼',
 '되',
 '두',
 '둘',
 '둠',
 '둥',
 '뒷',
 '듀',
 '드',
 '들',
 '듬',
 '등',
 '디',
 '딕',
 '딜',
 '딤',
 '딩',
 '따',
 '딱',
 '땅',
 '때',
 '땡',
 '떠',
 '떡',
 '떳',
 '떼',
 '또',
 '똑',
 '똘',
 '똣',
 '똥',
 '뙤',
 '뚜',
 '뚝',
 '뚠',
 '뚱',
 '뜨',
 '뜬',
 '뜰',
 '뜻',
 '띠',
 '라',
 '락',
 '란',
 '람',
 '랍',
 '랑',
 '래',
 '랜',
 '램',
 '러',
 '럭',
 '런',
 '레',
 '렌',
 '렐',
 '렛',
 '로',
 '록',
 '론',
 '롤',
 '롯',
 '롱',
 '롸',
 '료',
 '룡',
 '루',
 '룸',
 '뤼',
 '류',
 '르',
 '릇',
 '리',
 '린',
 '릴',
 '림',
 '릿',
 '마',
 '막',
 '만',
 '말',
 '맑',
 '맘',
 '맛',
 '망',
 '맞',
 '매',
 '맥',
 '맨',
 '맵',
 '맹',
 '머',
 '먹',
 '멈',
 '멋',
 '멍',
 '메',
 '멕',
 '멘',
 '멜',
 '멧',
 '면',
 '멸',
 '명',
 '모',
 '목',
 '몬',
 '몰',
 '몸',
 '못',
 '몽',
 '뫼',
 '묘',
 '무',
 '묵',
 '문',
 '물',
 '뭉',
 '뮈',
 '뮤',
 '미',
 '민',
 '믿',
 '밀',
 '밈',
 '밍',
 '바',
 '박',
 '반',
 '발',
 '밝',
 '밤',
 '밥',
 '방',
 '밭',
 '배',
 '백',
 '뱃',
 '뱅',
 '버',
 '번',
 '벌',
 '범',
 '법',
 '베',
 '벤',
 '벨',
 '벳',
 '벵',
 '벼',
 '벽',
 '변',
 '별',
 '병',
 '볕',
 '보',
 '복',
 '볶',
 '본',
 '볼',
 '봄',
 '봅',
 '봉',
 '뵤',
 '부',
 '북',
 '분',
 '불',
 '붉',
 '붐',
 '붕',
 '뷔',
 '뷰',
 '브',
 '블',
 '비',
 '빅',
 '빈',
 '빌',
 '빗',
 '빙',
 '빛',
 '빠',
 '빨',
 '빵',
 '빼',
 '빽',
 '뻐',
 '뻘',
 '뼈',
 '뽀',
 '뽈',
 '뽕',
 '뿌',
 '뿐',
 '뿔',
 '쁘',
 '쁠',
 '삐',
 '사',
 '산',
 '살',
 '삼',
 '삿',
 '상',
 '새',
 '색',
 '샌',
 '샐',
 '샘',
 '샛',
 '생',
 '샤',
 '샨',
 '샷',
 '샹',
 '서',
 '석',
 '선',
 '설',
 '섬',
 '섭',
 '섯',
 '성',
 '섶',
 '세',
 '센',
 '셀',
 '셔',
 '셰',
 '소',
 '속',
 '손',
 '솔',
 '솜',
 '송',
 '솥',
 '쇠',
 '쇼',
 '숑',
 '수',
 '숙',
 '순',
 '숟',
 '숨',
 '숯',
 '숲',
 '쉐',
 '쉘',
 '쉬',
 '쉴',
 '쉼',
 '슁',
 '슈',
 '슌',
 '스',
 '슬',
 '승',
 '시',
 '식',
 '신',
 '실',
 '심',
 '십',
 '싱',
 '싸',
 '쌀',
 '쌈',
 '쌍',
 '쌔',
 '써',
 '썬',
 '썸',
 '쎄',
 '쎈',
 '쎌',
 '쏘',
 '쏠',
 '쏭',
 '쑤',
 '쑥',
 '쓰',
 '씨',
 '아',
 '악',
 '안',
 '알',
 '암',
 '압',
 '앙',
 '앞',
 '애',
 '앤',
 '앨',
 '앰',
 '앳',
 '앵',
 '야',
 '약',
 '얄',
 '얌',
 '양',
 '어',
 '억',
 '언',
 '얼',
 '엄',
 '업',
 '엉',
 '에',
 '엑',
 '엔',
 '엘',
 '엠',
 '엣',
 '엥',
 '여',
 '역',
 '연',
 '열',
 '염',
 '영',
 '옆',
 '예',
 '옐',
 '옛',
 '오',
 '옥',
 '온',
 '올',
 '옳',
 '옴',
 '옵',
 '옷',
 '옹',
 '와',
 '완',
 '왓',
 '왔',
 '왕',
 '외',
 '요',
 '욜',
 '용',
 '우',
 '운',
 '울',
 '움',
 '웃',
 '웅',
 '워',
 '원',
 '월',
 '웨',
 '웬',
 '웰',
 '위',
 '윈',
 '윌',
 '윗',
 '윙',
 '유',
 '육',
 '윤',
 '율',
 '으',
 '은',
 '을',
 '음',
 '읍',
 '응',
 '의',
 '이',
 '익',
 '인',
 '일',
 '임',
 '잇',
 '있',
 '자',
 '작',
 '잔',
 '잘',
 '잠',
 '장',
 '재',
 '쟁',
 '쟈',
 '쟝',
 '저',
 '적',
 '전',
 '절',
 '점',
 '접',
 '정',
 '제',
 '젠',
 '젤',
 '젬',
 '조',
 '족',
 '존',
 '좀',
 '좁',
 '종',
 '좋',
 '좌',
 '죠',
 '주',
 '죽',
 '준',
 '줄',
 '줌',
 '중',
 '쥬',
 '쥴',
 '즉',
 '즐',
 '즙',
 '지',
 '직',
 '진',
 '질',
 '짐',
 '집',
 '징',
 '짚',
 '짜',
 '짝',
 '짠',
 '짬',
 '짱',
 '쨍',
 '쩐',
 '쪼',
 '쪽',
 '쫑',
 '쭈',
 '쯔',
 '찌',
 '찐',
 '찜',
 '차',
 '착',
 '찬',
 '찰',
 '참',
 '찹',
 '창',
 '채',
 '챈',
 '챙',
 '챠',
 '챨',
 '처',
 '천',
 '철',
 '첨',
 '첫',
 '청',
 '체',
 '초',
 '촌',
 '촐',
 '촘',
 '총',
 '최',
 '쵸',
 '추',
 '축',
 '춘',
 '출',
 '춤',
 '충',
 '취',
 '츄',
 '츠',
 '치',
 '친',
 '칠',
 '칭',
 '카',
 '칸',
 '칼',
 '캐',
 '캘',
 '캠',
 '캡',
 '캣',
 '커',
 '컨',
 '컬',
 '컴',
 '컵',
 '케',
 '코',
 '콕',
 '콘',
 '콜',
 '콤',
 '콩',
 '쿠',
 '쿡',
 '쿤',
 '쿵',
 '퀴',
 '퀸',
 '큐',
 '크',
 '큰',
 '클',
 '키',
 '킨',
 '킴',
 '킵',
 '킹',
 '타',
 '탁',
 '탄',
 '탐',
 '탑',
 '탕',
 '태',
 '택',
 '탤',
 '탭',
 '탱',
 '터',
 '턴',
 '털',
 '텀',
 '텅',
 '테',
 '텍',
 '텐',
 '템',
 '토',
 '톡',
 '톨',
 '톰',
 '통',
 '투',
 '튀',
 '트',
 '특',
 '틈',
 '티',
 '틴',
 '팀',
 '팅',
 '파',
 '팍',
 '판',
 '팔',
 '팜',
 '팝',
 '팟',
 '팡',
 '팥',
 '패',
 '팩',
 '팰',
 '퍼',
 '펄',
 '페',
 '펜',
 '펠',
 '펭',
 '편',
 '평',
 '포',
 '폭',
 '폴',
 '폼',
 '퐁',
 '표',
 '푸',
 '풀',
 '풍',
 '퓨',
 '프',
 '플',
 '피',
 '핀',
 '필',
 '핏',
 '핑',
 '하',
 '학',
 '한',
 '할',
 '함',
 '핫',
 '항',
 '해',
 '핵',
 '핸',
 '햇',
 '행',
 '향',
 '허',
 '헛',
 '헝',
 '헤',
 '헬',
 '혀',
 '혁',
 '현',
 '협',
 '형',
 '혜',
 '호',
 '혹',
 '혼',
 '홀',
 '홈',
 '홋',
 '홍',
 '화',
 '환',
 '활',
 '황',
 '회',
 '횟',
 '효',
 '후',
 '훈',
 '훌',
 '훔',
 '휘',
 '휠',
 '휴',
 '흑',
 '흙',
 '흠',
 '흥',
 '희',
 '히',
 '힌',
 '힐',
 '힘',
 '힙',
 '힛'}

In [10]:
df_특 = df.copy()
df_수 = df.copy()
df_영 = df.copy()
df_한 = df.copy()
delete3 = []
delete4 = []
delete5 = []
delete6 = []

for i in range(len(df.index)):
    
    if df.iloc[i,1][0] != '(':
        delete3.append(i)
        
df_특 = df_특.drop(index = delete3, axis = 0)

for i in range(len(df.index)):
    
    if not df.iloc[i,1][0].isdecimal():
        delete4.append(i)
        
df_수 = df_수.drop(index = delete4, axis = 0)

for i in range(len(df.index)):
    
    if not df.iloc[i,1][0].encode().isalpha():
        delete5.append(i)
        
df_영 = df_영.drop(index = delete5, axis = 0)

for i in range(len(df.index)):
    
    if df.iloc[i,1][0].isalpha() == df.iloc[i,1][0].encode().isalpha():
        delete6.append(i)
        
df_한 = df_한.drop(index = delete6, axis = 0)

In [11]:
df_특 = df_특.sort_values(by = ['가맹점명'])

In [12]:
df_수 = df_수.sort_values(by = ['가맹점명'])

In [13]:
df_영 = df_영.sort_values(by = ['가맹점명'])

In [14]:
df_한 = df_한.sort_values(by = ['가맹점명'])

In [15]:
# 한글 영어 숫자 특문 순서

df_ali = pd.concat([df_한,df_영,df_수,df_특])

In [16]:
df_ali

,행정시,가맹점명,전화번호,주소,데이터기준일자
6553,제주시,味s7,064-748-8007,제주특별자치도 제주시 일주서로 7831,2022-03-31
1641,제주시,美양양,064-722-3332,제주특별자치도 제주시 도남로 62,2022-03-31
13905,서귀포시,가가멜,070-7798-2360,제주특별자치도 서귀포시 문부로 8,2022-03-31
14226,서귀포시,가가호호,NaN,제주특별자치도 서귀포시 남원읍 태위로 87,2022-03-31
9007,서귀포시,가고파,064-762-5331,제주특별자치도 서귀포시 중정로91번길 25-2,2022-03-31
...,...,...,...,...,...
2996,서귀포시,(주)호텔롯데 롯데호텔제주 델리카한스,064-731-1000,제주특별자치도 서귀포시 중문관광로72번길 35,2022-03-31
2998,서귀포시,(주)호텔롯데델리카한스/은련,064-731-1000,제주특별자치도 서귀포시 중문관광로72번길 35,2022-03-31
6522,제주시,(주)후사부,064-748-6311,제주특별자치도 제주시 신대로14길 35,2022-03-31
6523,제주시,(주)후사부,064-748-6311,제주특별자치도 제주시 신대로14길 41,2022-03-31
1625,제주시,(파인힐)솔동산,064-722-3023,제주특별자치도 제주시 중앙로 57,2022-03-31

In [17]:
df_ali['전화번호'] = df_ali['전화번호'].fillna('0-0-0')

In [18]:
df_ali

,행정시,가맹점명,전화번호,주소,데이터기준일자
6553,제주시,味s7,064-748-8007,제주특별자치도 제주시 일주서로 7831,2022-03-31
1641,제주시,美양양,064-722-3332,제주특별자치도 제주시 도남로 62,2022-03-31
13905,서귀포시,가가멜,070-7798-2360,제주특별자치도 서귀포시 문부로 8,2022-03-31
14226,서귀포시,가가호호,0-0-0,제주특별자치도 서귀포시 남원읍 태위로 87,2022-03-31
9007,서귀포시,가고파,064-762-5331,제주특별자치도 서귀포시 중정로91번길 25-2,2022-03-31
...,...,...,...,...,...
2996,서귀포시,(주)호텔롯데 롯데호텔제주 델리카한스,064-731-1000,제주특별자치도 서귀포시 중문관광로72번길 35,2022-03-31
2998,서귀포시,(주)호텔롯데델리카한스/은련,064-731-1000,제주특별자치도 서귀포시 중문관광로72번길 35,2022-03-31
6522,제주시,(주)후사부,064-748-6311,제주특별자치도 제주시 신대로14길 35,2022-03-31
6523,제주시,(주)후사부,064-748-6311,제주특별자치도 제주시 신대로14길 41,2022-03-31
1625,제주시,(파인힐)솔동산,064-722-3023,제주특별자치도 제주시 중앙로 57,2022-03-31

In [20]:
six = 0
sev = 0



for i in range(len(df_ali.index)):
    if 600 <= int(df_ali['전화번호'][i].split('-')[1]) <= 699:
        six += 1
        
    if 700 <= int(df_ali['전화번호'][i].split('-')[1]) <= 799:
        sev += 1

print(six)
print(sev)

2
13307